openapi: "3.0.0"
info:
  version: 1.0.0
  title: Brakdag API
paths:
  /bronnen:
    get:
      summary: Alle bronnen in een lijst
      operationId: lijstBronnen
      produces:
        - application/json
      responses:
        '200':
